import "@/styles/globals.css";
import "@/styles/icons.css";

import { Lato, Quicksand } from 'next/font/google';

import type { Metadata } from "next";

// Define the Quicksand font
const quicksand = Quicksand({
  subsets: ['latin']
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['400']  // Example: '400' for regular and '700' for bold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} font-fallback`}>{children}</body>
    </html>
  );
}